### ISSUE TITLE
How to setup test environment

### ISSUE THREAD

**Issue by TatriX** [quickdocs/quickdocs-server#1]
I would like to fix some things in the quickdocs and to make it I need a test environment. So I had tried to make one using quickdocs-updater without success.

If there is a simple way to get the test environment which doesn't require configuring docker and downloading thousands of packages? Or maybe I'm missing something obvious?

Thank you.

**Comment by fourier** [comment]
Bump this question. Would like to hack as well.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
Maybe this should come with a script that automatically installs all the dependencies and configures them. There are a couple of things I can't figure out from reading the source, such as:

* Which HTTP server this uses (Woo, Hunchentoot, something else?) and where this is controlled in the source.
* How the server is launched (apparently `quickdocs-server:start` is called with the arguments for `clack:clackup`, but which arguments are used, and where is this controlled?)

I just noticed right now that a large percentage of the available software for running Web sites on Common Lisp is written by one person: Eitaro Fukamachi. He's not only the author of Quickdocs, but also of Woo, Caveman, Clack, Datafly, CL-DBI, SXQL, and more. He's maintaining the whole Web stack all by himself. Perhaps he's stretched a little thin.

**Comment by TatriX** [comment]
CL is dead 8(
